#!/usr/bin/env bash
# Opens ArgoCD, Grafana, Prometheus and Kibana on THIS computer, and prints every login.
#   bash scripts/eks-open.sh        (leave it running; Ctrl+C closes all of them)
#
# These tools are deliberately not on the internet: this environment has no HTTPS, and Grafana, Kibana and
# ArgoCD all have admin logins. `kubectl port-forward` reaches them through your own AWS login instead.
# Change a port without editing the file:  GRAFANA_PORT=3400 bash scripts/eks-open.sh
set -uo pipefail

CLUSTER="aws-eks-gitops-platform-dev"
REGION="eu-north-1"
ARGO_PORT="${ARGO_PORT:-8443}"
GRAFANA_PORT="${GRAFANA_PORT:-3300}"
PROM_PORT="${PROM_PORT:-9091}"
KIBANA_PORT="${KIBANA_PORT:-5601}"

aws eks update-kubeconfig --name "$CLUSTER" --region "$REGION" >/dev/null || { echo "Cluster $CLUSTER not found. Run: bash scripts/eks-up.sh"; exit 1; }

pids=()
cleanup() { for p in "${pids[@]}"; do kill "$p" 2>/dev/null; done; echo; echo "Closed."; }
trap cleanup EXIT INT TERM

# forward <name> <namespace> <service> <local port> <service port>
forward() {
  if kubectl get svc "$3" -n "$2" >/dev/null 2>&1; then
    kubectl port-forward -n "$2" "svc/$3" "$4:$5" >/dev/null 2>&1 &
    pids+=("$!")
    printf '  %-11s ready\n' "$1"
  else
    printf '  %-11s NOT READY YET (still being installed by Argo CD: try again in a few minutes)\n' "$1"
  fi
}

echo "Opening..."
forward ArgoCD     argocd     argocd-server                          "$ARGO_PORT"    443
forward Grafana    monitoring monitoring-grafana                     "$GRAFANA_PORT" 80
forward Prometheus monitoring monitoring-kube-prometheus-prometheus  "$PROM_PORT"    9090
forward Kibana     logging    logging-kb-http                        "$KIBANA_PORT"  5601

# the logins
argo_pw=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' 2>/dev/null | base64 -d 2>/dev/null)
kibana_pw=$(kubectl -n logging get secret logging-es-elastic-user -o jsonpath='{.data.elastic}' 2>/dev/null | base64 -d 2>/dev/null)
grafana_json=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id aws-eks-gitops-platform/dev/grafana-admin --query SecretString --output text 2>/dev/null)
grafana_pw=$(printf '%s' "$grafana_json" | python3 -c 'import sys,json; print(json.load(sys.stdin)["admin-password"])' 2>/dev/null)
app=$(kubectl get ingress tasks -n tasks -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null)
app_url="not ready yet"; [[ -n "$app" ]] && app_url="http://$app"

cat << TXT

  The app         $app_url
  ArgoCD          https://localhost:$ARGO_PORT        admin / ${argo_pw:-<not ready yet>}
  Grafana         http://localhost:$GRAFANA_PORT         admin / ${grafana_pw:-<not ready yet>}     (dashboard: "Tasks app")
  Prometheus      http://localhost:$PROM_PORT          (no login; Status > Targets, Alerts)
  Kibana          https://localhost:$KIBANA_PORT        elastic / ${kibana_pw:-<not ready yet>}     (Discover: data view "Kubernetes logs")

  ArgoCD and Kibana use certificates from the cluster itself, so the browser warns once: choose to continue.
  Grafana's password is in AWS Secrets Manager (aws-eks-gitops-platform/dev/grafana-admin), generated by AWS.

  Press Ctrl+C to close everything.
TXT

[[ ${#pids[@]} -eq 0 ]] && exit 1
wait
